[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "finalproject"
requires-python = ">=3.12"
version = "1.0"


dependencies = [
    "jupyter", 
    "pandas",
    "matplotlib",
    "scipy",  
    "seaborn",
    "scipy",
    "scikit-learn" 
]

[project.optional-dependencies]
dev = [     "tox",
    "finalproject[lint]",
    "finalproject[test]",
    "finalproject[doc]",
    "finalproject[build]",
]
lint = [
    "mypy",
    "ruff",
]
test = [
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
    "coverage[toml]==7.3.1",
    "pytest-html==4.1.1"
]
doc = [
]
build = [
    "build>=1.2.2",
]

[tool.ruff]
line-length = 120
src = ["src"]
extend-exclude = [
    "conf.py",
]
target-version = "py312"
lint.select = ["ALL"]
lint.ignore = [
    "COM812",   
    "ISC001",   
    "ANN101",   
    "PT001",    
    "PT004",    
    "PT005",    
    "PT023",    
    "D415",     
    "D416",     
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = [
    "S101", 
    "D103", 
]
"**/__init__.py" = [
    "F401", 
    "F403", 
    "D104", 
]
"docs/**" = [
    "INP001",   
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
disallow_untyped_defs = true 
warn_unused_ignores = true
ignore_missing_imports = true
exclude = [
    "finalproject\\d+", 
    "venv.*/",
    "build/",
    "dist/",
]

